export const metadata = {
  title: 'katalog electronic',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>        
        {children}
      </body>
    </html>
  )
}
